# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: changeme

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: backend
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeme
      ME_CONFIG_MONGODB_URL: mongodb://backend:changeme@mongo:27017/

# engine://user:password@host:port/
